<script setup lang="ts">
import { ref, onMounted } from 'vue'
import UploadImage from './UploadImage.vue'
import { ElMessage } from 'element-plus'
import { uploadAndAnalyze, publishOutfit } from '@/api/outfit'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
import { MagicStick, Share, Lock, Star, ArrowRight } from '@element-plus/icons-vue'

const router = useRouter()
const userStore = useUserStore()
// AI 分析结果
const aiResult = ref<any>(null)
// 状态控制
const uploading = ref(false)
const publishing = ref(false)
// 模拟的时尚指数评分
const fashionScore = ref(92)

// 发布表单状态
const publishForm = ref({
  title: '',
  occasion: '日常',
  season: '',
  temperatureRange: ''
})

onMounted(async () => {
  // 初始化逻辑
})

// 处理上传与分析
const handleUpload = async (data: any) => {
  uploading.value = true
  // 随机生成时尚指数，增强互动性
  fashionScore.value = Math.floor(Math.random() * 12) + 88 
  
  try {
    const res: any = await uploadAndAnalyze([data.compressedFile])
    
    // 补全保底值
    const season = res.season && res.season !== 'null' ? res.season : '春秋'
    const temperatureRange = res.temperatureRange && res.temperatureRange !== 'null' ? res.temperatureRange : '舒适'
    
    aiResult.value = {
      ...res,
      season,
      temperatureRange,
      tempImage: data.base64Data
    }
    
    // 初始化表单
    publishForm.value.title = '我的校园穿搭'
    publishForm.value.occasion = '日常'
    publishForm.value.season = season
    publishForm.value.temperatureRange = temperatureRange
    
    ElMessage({
      message: 'AI 分析报告已生成',
      type: 'success',
      customClass: 'fashion-message'
    })
  } catch (e) {
    ElMessage.error('AI 解析失败，请重试')
  } finally {
    uploading.value = false
  }
}

const emit = defineEmits(['success'])

// 处理发布或私密保存
const handlePublish = async (status: 'PUBLISHED' | 'PRIVATE') => {
  if (!aiResult.value) return
  
  if (!userStore.token) {
    ElMessage.warning('请登录后再保存穿搭')
    router.push('/login')
    return
  }

  publishing.value = true
  try {
    const data = {
      title: publishForm.value.title || '我的校园穿搭',
      description: aiResult.value.suggestion,
      imageUrls: aiResult.value.imageUrls,
      styleTags: aiResult.value.styleTags,
      colorTags: aiResult.value.colorTags,
      itemKeywords: aiResult.value.itemKeywords,
      occasion: publishForm.value.occasion,
      status: status,
      season: aiResult.value.season,
      temperatureRange: aiResult.value.temperatureRange,
      aiAnalysis: JSON.stringify(aiResult.value)
    }
    await publishOutfit(data)
    
    aiResult.value = null
    emit('success')

    if (status === 'PUBLISHED') {
      ElMessage.success('穿搭灵感已同步至社区')
      router.push('/')
    } else {
      ElMessage.success('已妥善收纳至私人衣橱')
    }
  } catch (e: any) {
    ElMessage.error(e.message || '操作失败')
  } finally {
    publishing.value = false
  }
}
</script>

<template>
  <div class="ai-card-wrapper">
    <!-- 1. 上传区 -->
    <div v-if="!aiResult" class="upload-section animate-scale-up">
      <div class="section-header">
        <span class="accent-badge">AI 智慧赋能</span>
        <h2 class="main-title">穿搭基因提取</h2>
        <p class="sub-title">上传图片，即刻解锁专属于你的穿搭美学报告</p>
      </div>
      
      <div v-loading="uploading" element-loading-text="AI 正在深度解析你的穿搭风格..." class="upload-content">
        <UploadImage @upload-success="handleUpload" />
      </div>
    </div>

    <!-- 2. 结果报告区 -->
    <div v-else class="report-section animate-fade-in">
      <!-- 报告顶部：科技时尚感卡片 -->
      <div class="report-header">
        <div class="header-info">
          <h3 class="report-title"><el-icon><MagicStick /></el-icon> 穿搭分析报告</h3>
          <p class="report-subtitle">Generated by Campus AI Engine</p>
        </div>
        <!-- 时尚指数微互动 -->
        <div class="score-badge">
          <div class="score-value">{{ fashionScore }}</div>
          <div class="score-label">时尚指数</div>
        </div>
      </div>

      <div class="report-body">
        <!-- 图片与预览模块 -->
        <div class="preview-grid">
          <div class="main-image-card">
            <img :src="aiResult.tempImage" alt="原图" class="main-img" />
            <div class="scan-overlay"></div>
          </div>
          
          <div class="extracted-items">
            <span class="mini-title">提取结果 ({{ aiResult.imageUrls?.length || 0 }})</span>
            <div class="img-list custom-scrollbar">
              <el-image 
                v-for="url in aiResult.imageUrls" 
                :key="url" 
                :src="url" 
                class="thumb-img"
                fit="cover" 
                :preview-src-list="aiResult.imageUrls" 
              />
            </div>
          </div>
        </div>

        <!-- 表单编辑区 -->
        <div class="form-grid">
          <div class="form-item">
            <span class="field-label">穿搭名称</span>
            <el-input 
              v-model="publishForm.title" 
              placeholder="为你的时尚起个名字" 
              maxlength="20" 
              show-word-limit
              class="fashion-input"
            />
          </div>
          
          <div class="form-item">
            <span class="field-label">适宜场景</span>
            <el-select v-model="publishForm.occasion" class="fashion-select">
              <el-option label="📖 校园日常" value="日常" />
              <el-option label="☕ 浪漫约会" value="约会" />
              <el-option label="👔 正式/面试" value="面试/正式" />
              <el-option label="🎧 图书馆" value="图书馆" />
              <el-option label="🏃 运动活力" value="运动" />
            </el-select>
          </div>
        </div>

        <!-- 穿搭属性标签 -->
        <div class="tags-section">
          <div class="tag-group">
            <span class="group-label">风格特征</span>
            <div class="tags-wrapper">
              <span v-for="tag in aiResult.styleTags" :key="tag" class="style-tag">{{ tag }}</span>
            </div>
          </div>

          <div class="tag-group">
            <span class="group-label">核心单品</span>
            <div class="tags-wrapper">
              <span v-for="item in aiResult.itemKeywords" :key="item" class="item-tag">{{ item }}</span>
            </div>
          </div>
        </div>

        <!-- 适宜气候 -->
        <div class="weather-info">
          <div class="weather-item">
            <span class="weather-label">推荐季节</span>
            <span class="weather-value season">{{ aiResult.season }}</span>
          </div>
          <div class="weather-item">
            <span class="weather-label">推荐气温</span>
            <span class="weather-value temperature">{{ aiResult.temperatureRange }}</span>
          </div>
        </div>

        <!-- AI 建议报告 -->
        <div class="suggestion-box">
          <div class="box-glow"></div>
          <div class="suggestion-header">
            <el-icon class="ai-icon"><Star /></el-icon>
            <span>AI 时尚穿搭指南</span>
          </div>
          <p class="suggestion-text">{{ aiResult.suggestion }}</p>
        </div>
      </div>

      <!-- 底部操作按钮 -->
      <div class="report-actions">
        <div class="action-buttons">
          <el-button 
            type="primary" 
            class="btn-primary flex-1" 
            :loading="publishing" 
            @click="handlePublish('PUBLISHED')"
          >
            <el-icon><Share /></el-icon> 发布至社区
          </el-button>
          
          <el-button 
            class="btn-secondary flex-1" 
            :loading="publishing" 
            @click="handlePublish('PRIVATE')"
          >
            <el-icon><Lock /></el-icon> 存入私人衣橱
          </el-button>
        </div>
        
        <button class="btn-text-link" @click="aiResult = null">
          重新分析 <el-icon><ArrowRight /></el-icon>
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.ai-card-wrapper {
  width: 100%;
  max-width: 520px;
  margin: 0 auto;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* 1. 上传区样式 */
.section-header {
  text-align: center;
  margin-bottom: 24px;
}

.accent-badge {
  display: inline-block;
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 1px;
  padding: 4px 12px;
  background: rgba(var(--el-color-primary-rgb), 0.12);
  color: var(--el-color-primary);
  border-radius: 20px;
  margin-bottom: 10px;
}

.main-title {
  font-size: 22px;
  font-weight: 800;
  color: var(--el-text-color-primary);
  letter-spacing: -0.5px;
  margin-bottom: 6px;
}

.sub-title {
  font-size: 13px;
  color: var(--el-text-color-secondary);
}

/* 2. 报告区样式 */
.report-section {
  background: rgba(255, 255, 255, 0.8);
  backdrop-filter: blur(30px);
  border: 1px solid rgba(255, 255, 255, 0.5);
  border-radius: 28px;
  padding: 24px;
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.dark .report-section {
  background: rgba(24, 24, 27, 0.8);
  border: 1px solid rgba(255, 255, 255, 0.05);
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.4);
}

.report-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid rgba(0, 0, 0, 0.05);
  padding-bottom: 16px;
  margin-bottom: 20px;
}

.dark .report-header {
  border-color: rgba(255, 255, 255, 0.05);
}

.report-title {
  font-size: 18px;
  font-weight: 800;
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--el-text-color-primary);
}

.report-title .el-icon {
  color: var(--el-color-primary);
}

.report-subtitle {
  font-size: 11px;
  color: var(--el-text-color-secondary);
  font-weight: 500;
  margin-top: 2px;
}

/* 时尚指数勋章 */
.score-badge {
  background: linear-gradient(135deg, var(--el-color-primary) 0%, #a855f7 100%);
  color: white;
  width: 54px;
  height: 54px;
  border-radius: 16px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  box-shadow: 0 8px 20px -4px rgba(var(--el-color-primary-rgb), 0.4);
}

.score-value {
  font-size: 20px;
  font-weight: 900;
  line-height: 1.1;
}

.score-label {
  font-size: 9px;
  opacity: 0.9;
  font-weight: 600;
  transform: scale(0.9);
}

/* 图片网格 */
.preview-grid {
  display: flex;
  gap: 16px;
  margin-bottom: 20px;
}

.main-image-card {
  width: 110px;
  height: 140px;
  border-radius: 16px;
  overflow: hidden;
  position: relative;
  border: 1px solid rgba(0, 0, 0, 0.05);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
}

.main-img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.scan-overlay {
  position: absolute;
  inset: 0;
  background: linear-gradient(to bottom, rgba(var(--el-color-primary-rgb), 0.2), transparent);
  pointer-events: none;
}

.extracted-items {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  background: rgba(0, 0, 0, 0.02);
  padding: 12px;
  border-radius: 16px;
  border: 1px solid rgba(0, 0, 0, 0.03);
}

.dark .extracted-items {
  background: rgba(255, 255, 255, 0.02);
  border-color: rgba(255, 255, 255, 0.05);
}

.mini-title {
  font-size: 11px;
  font-weight: 700;
  color: var(--el-text-color-secondary);
  text-transform: uppercase;
  margin-bottom: 8px;
}

.img-list {
  display: flex;
  gap: 8px;
  overflow-x: auto;
  padding-bottom: 4px;
}

.thumb-img {
  width: 42px;
  height: 42px;
  border-radius: 8px;
  cursor: pointer;
  border: 1px solid rgba(255, 255, 255, 0.8);
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
  transition: transform 0.2s ease;
}

.thumb-img:hover {
  transform: scale(1.08);
}

/* 表单样式优化 */
.form-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
  margin-bottom: 20px;
}

.field-label {
  display: block;
  font-size: 12px;
  font-weight: 700;
  color: var(--el-text-color-regular);
  margin-bottom: 6px;
}

.fashion-input :deep(.el-input__wrapper),
.fashion-select :deep(.el-input__wrapper) {
  background: rgba(0, 0, 0, 0.03);
  border-radius: 10px;
  box-shadow: none !important;
  border: 1px solid transparent;
  transition: all 0.3s ease;
}

.dark .fashion-input :deep(.el-input__wrapper),
.dark .fashion-select :deep(.el-input__wrapper) {
  background: rgba(255, 255, 255, 0.05);
}

.fashion-input :deep(.el-input__wrapper:hover),
.fashion-select :deep(.el-input__wrapper:hover),
.fashion-input :deep(.el-input__wrapper.is-focus),
.fashion-select :deep(.el-input__wrapper.is-focus) {
  border-color: var(--el-color-primary);
  background: transparent;
}

/* 标签部分 */
.tags-section {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin-bottom: 20px;
}

.tag-group {
  display: flex;
  align-items: flex-start;
  gap: 12px;
}

.group-label {
  font-size: 12px;
  font-weight: 700;
  color: var(--el-text-color-regular);
  width: 60px;
  padding-top: 4px;
}

.tags-wrapper {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.style-tag {
  font-size: 11px;
  font-weight: 600;
  padding: 4px 10px;
  background: rgba(var(--el-color-primary-rgb), 0.08);
  color: var(--el-color-primary);
  border-radius: 12px;
  border: 1px solid rgba(var(--el-color-primary-rgb), 0.15);
}

.item-tag {
  font-size: 11px;
  font-weight: 500;
  padding: 4px 10px;
  background: rgba(0, 0, 0, 0.04);
  color: var(--el-text-color-regular);
  border-radius: 12px;
}

.dark .item-tag {
  background: rgba(255, 255, 255, 0.05);
}

/* 气候信息 */
.weather-info {
  display: flex;
  background: rgba(0, 0, 0, 0.02);
  border-radius: 16px;
  padding: 12px;
  margin-bottom: 20px;
  border: 1px solid rgba(0, 0, 0, 0.03);
}

.dark .weather-info {
  background: rgba(255, 255, 255, 0.02);
  border-color: rgba(255, 255, 255, 0.05);
}

.weather-item {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.weather-item:first-child {
  border-right: 1px solid rgba(0, 0, 0, 0.05);
}

.dark .weather-item:first-child {
  border-color: rgba(255, 255, 255, 0.05);
}

.weather-label {
  font-size: 11px;
  color: var(--el-text-color-secondary);
  margin-bottom: 4px;
}

.weather-value {
  font-size: 14px;
  font-weight: 700;
}

.weather-value.season {
  color: #e6a23c;
}

.weather-value.temperature {
  color: #f56c6c;
}

/* AI 建议框 */
.suggestion-box {
  position: relative;
  background: linear-gradient(135deg, rgba(var(--el-color-primary-rgb), 0.05), rgba(168, 85, 247, 0.05));
  border: 1px solid rgba(var(--el-color-primary-rgb), 0.15);
  border-radius: 16px;
  padding: 16px;
  margin-bottom: 24px;
  overflow: hidden;
}

.suggestion-header {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 13px;
  font-weight: 700;
  color: var(--el-color-primary);
  margin-bottom: 8px;
}

.suggestion-text {
  font-size: 13px;
  line-height: 1.6;
  color: var(--el-text-color-regular);
  position: relative;
  z-index: 1;
}

/* 按钮及交互 */
.report-actions {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
}

.action-buttons {
  display: flex;
  gap: 12px;
  width: 100%;
}

.btn-primary {
  height: 44px;
  border-radius: 22px;
  font-weight: 700;
  background: linear-gradient(135deg, var(--el-color-primary) 0%, #818cf8 100%);
  border: none;
  box-shadow: 0 10px 20px -5px rgba(var(--el-color-primary-rgb), 0.3);
  transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
}

.btn-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 15px 25px -5px rgba(var(--el-color-primary-rgb), 0.4);
}

.btn-secondary {
  height: 44px;
  border-radius: 22px;
  font-weight: 700;
  background: rgba(0, 0, 0, 0.05);
  color: var(--el-text-color-primary);
  border: 1px solid rgba(0, 0, 0, 0.05);
  transition: all 0.3s ease;
}

.dark .btn-secondary {
  background: rgba(255, 255, 255, 0.08);
  border: 1px solid rgba(255, 255, 255, 0.05);
}

.btn-secondary:hover {
  background: rgba(0, 0, 0, 0.08);
  transform: translateY(-2px);
}

.dark .btn-secondary:hover {
  background: rgba(255, 255, 255, 0.12);
}

.btn-text-link {
  font-size: 12px;
  color: var(--el-text-color-secondary);
  background: none;
  border: none;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 4px;
  transition: color 0.2s ease;
}

.btn-text-link:hover {
  color: var(--el-color-primary);
}

/* 动画定义 */
.animate-scale-up {
  animation: scaleUp 0.5s cubic-bezier(0.16, 1, 0.3, 1);
}

@keyframes scaleUp {
  from { opacity: 0; transform: scale(0.95); }
  to { opacity: 1; transform: scale(1); }
}

.animate-fade-in {
  animation: fadeIn 0.6s ease-out;
}

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

.custom-scrollbar::-webkit-scrollbar {
  height: 4px;
}
.custom-scrollbar::-webkit-scrollbar-thumb {
  background: rgba(0, 0, 0, 0.1);
  border-radius: 10px;
}
.dark .custom-scrollbar::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.1);
}
</style>

