-- 创建数据库
CREATE DATABASE IF NOT EXISTS campus_outfit CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE campus_outfit;

-- 1. 用户表
CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` VARCHAR(50) NOT NULL COMMENT '用户名',
  `password` VARCHAR(100) NOT NULL COMMENT '密码',
  `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `avatar` VARCHAR(512) DEFAULT NULL COMMENT '头像',
  `nickname` VARCHAR(50) DEFAULT NULL COMMENT '昵称',
  `bio` VARCHAR(200) DEFAULT NULL COMMENT '个人简介',
  `gender` VARCHAR(10) DEFAULT NULL COMMENT '性别',
  `school` VARCHAR(100) DEFAULT NULL COMMENT '所在学校',
  `location` VARCHAR(100) DEFAULT NULL COMMENT '地理位置',
  `role` ENUM('NORMAL', 'ADMIN') DEFAULT 'NORMAL' COMMENT '角色',
  `follow_count` INT NOT NULL DEFAULT 0 COMMENT '关注数',
  `fan_count` INT NOT NULL DEFAULT 0 COMMENT '粉丝数',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';